id: A432A5B89
base_file: fAC7A.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:51:08.667826
  last_modified_at: 2022-05-30 18:51:08.667836
