id: A432A5B89
base_file: fE4F4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:51:08.674700
  last_modified_at: 2022-05-30 18:51:08.674703
