id: A432A5B89
base_file: f021D.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:51:08.655505
  last_modified_at: 2022-05-30 18:51:08.655513
