id: A432A5B89
base_file: f6035.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:51:08.663754
  last_modified_at: 2022-05-30 18:51:08.663761
